// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillService.Data;

#nullable disable

namespace SkillService.Migrations
{
    [DbContext(typeof(SkillDbContext))]
    [Migration("20251214065222_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillService.Models.EmployeeReference", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("EmployeeReferences");
                });

            modelBuilder.Entity("SkillService.Models.EmployeeSkill", b =>
                {
                    b.Property<Guid>("EmployeeSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TrainingNeeded")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeSkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("EmployeeId", "SkillId")
                        .IsUnique();

                    b.ToTable("EmployeeSkills");
                });

            modelBuilder.Entity("SkillService.Models.Skill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SkillId");

                    b.HasIndex("SkillName")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SkillName = "C#"
                        },
                        new
                        {
                            SkillId = new Guid("22222222-2222-2222-2222-222222222222"),
                            SkillName = "Java"
                        },
                        new
                        {
                            SkillId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SkillName = "Python"
                        },
                        new
                        {
                            SkillId = new Guid("44444444-4444-4444-4444-444444444444"),
                            SkillName = "JavaScript"
                        },
                        new
                        {
                            SkillId = new Guid("55555555-5555-5555-5555-555555555555"),
                            SkillName = "SQL"
                        },
                        new
                        {
                            SkillId = new Guid("66666666-6666-6666-6666-666666666666"),
                            SkillName = "React"
                        },
                        new
                        {
                            SkillId = new Guid("77777777-7777-7777-7777-777777777777"),
                            SkillName = "Angular"
                        },
                        new
                        {
                            SkillId = new Guid("88888888-8888-8888-8888-888888888888"),
                            SkillName = "Node.js"
                        },
                        new
                        {
                            SkillId = new Guid("99999999-9999-9999-9999-999999999999"),
                            SkillName = "Docker"
                        },
                        new
                        {
                            SkillId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            SkillName = "Kubernetes"
                        });
                });

            modelBuilder.Entity("SkillService.Models.EmployeeSkill", b =>
                {
                    b.HasOne("SkillService.Models.Skill", "Skill")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SkillService.Models.Skill", b =>
                {
                    b.Navigation("EmployeeSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
